### ISSUE TITLE
Backlight not working when I upload sample code

### ISSUE THREAD

**Issue by joshuaokpako** [LilyGO/TTGO-TS-V1.2#21]
I am using the 1.8" and 1.44" TFT screen and when I upload the sample code, the backlight goes off completely but the program works fine and shows the correct display on the screen but the back light doesn't work

**Comment by sfambach** [comment]
Can you post your code, this could help. Check the pin for backlight this pin 27. Set it to output and to high value.

**Comment by joshuaokpako** [comment]
Yes thank you that was the issue. It worked.  I did not know that pin 27 was for the backlight
